services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env.sample
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./postgres_data:/var/bk/
    env_file:
      - .env.sample.db

#  nginx:
#    build: ./nginx
#    volumes:
#      - static_volume:/home/app/web/staticfiles
#    ports:
#      - 8000:80
#    depends_on:
#      - web


volumes:
  postgres_data:
  static_volume: