version: '3'

services:
  web:
    build: .
    volumes:
      - static_volume:/home/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  redis:
    image: "redis:alpine"

volumes:
  postgres_data:
  static_volume: